// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-tXwpdsnNMlXHCzK8wvaAGIRiE0Un67A',
    appId: '1:333331472361:web:f3f48d0c988377b07f3578',
    messagingSenderId: '333331472361',
    projectId: 'exitoxyv2',
    authDomain: 'exitoxyv2.firebaseapp.com',
    storageBucket: 'exitoxyv2.firebasestorage.app',
    measurementId: 'G-MDDQTZRVHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCag-7841CRfBOYlcxQmjr3Wok59LYdLng',
    appId: '1:333331472361:android:3ce8e10e96c9da8a7f3578',
    messagingSenderId: '333331472361',
    projectId: 'exitoxyv2',
    storageBucket: 'exitoxyv2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUPFs90pOiOq-wk7IbIghhCqTJQ3dy7vk',
    appId: '1:333331472361:ios:31ac51f93ce3fa347f3578',
    messagingSenderId: '333331472361',
    projectId: 'exitoxyv2',
    storageBucket: 'exitoxyv2.firebasestorage.app',
    iosClientId: '333331472361-fgb4arjpa955v91np19q9tlgnvt0t5mf.apps.googleusercontent.com',
    iosBundleId: 'com.example.kititV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUPFs90pOiOq-wk7IbIghhCqTJQ3dy7vk',
    appId: '1:333331472361:ios:31ac51f93ce3fa347f3578',
    messagingSenderId: '333331472361',
    projectId: 'exitoxyv2',
    storageBucket: 'exitoxyv2.firebasestorage.app',
    iosClientId: '333331472361-fgb4arjpa955v91np19q9tlgnvt0t5mf.apps.googleusercontent.com',
    iosBundleId: 'com.example.kititV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-tXwpdsnNMlXHCzK8wvaAGIRiE0Un67A',
    appId: '1:333331472361:web:36cb8e272ea486847f3578',
    messagingSenderId: '333331472361',
    projectId: 'exitoxyv2',
    authDomain: 'exitoxyv2.firebaseapp.com',
    storageBucket: 'exitoxyv2.firebasestorage.app',
    measurementId: 'G-D46T8D26E7',
  );

}
